### ISSUE TITLE
Unable to load shared library 'discord_game_sdk'

### ISSUE THREAD

**Issue by RHeynsZa** [cswendrowski/FoundryVTT-Discord-Rich-Presence#25]
This still isnt resolved

https://github.com/cswendrowski/FoundryVTT-Discord-Rich-Presence/issues/23

```
Created DiscordManager e5f71692-40e9-4e5e-8d90-305a3497c4fc
e5f71692-40e9-4e5e-8d90-305a3497c4fc - Creating new Discord instance
Unhandled exception. System.TypeInitializationException: The type initializer for 'RichPresenceApi.DiscordManager' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'discord_game_sdk' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libdiscord_game_sdk: cannot open shared object file: No such file or directory
   at DiscordSdk.Discord.DiscordCreate(UInt32 version, FFICreateParams& createParams, IntPtr& manager)
   at DiscordSdk.Discord..ctor(Int64 clientId, UInt64 flags) in D:\Programming\Git\FoundryVTT-Discord-Rich-Presence\LocalApi\DiscordSdk\Core.cs:line 1060
```

**Comment by cswendrowski** [comment]
@RHeynsZa what OS?

**Comment by RHeynsZa** [comment]
Linux, Ubuntu 20

**Comment by NahmiiVuhuni** [comment]
Is there a specific version of dotnet we should try running this against? I would love to use this but we haven't seemed to find any support, and it's apparently broken on both Windows and Linux in some cases.

**Comment by LiquidPL** [comment]
This is happening because the latest release of the app is missing the Linux Discord Game SDK library, get it from [here](https://discord.com/developers/docs/game-sdk/sdk-starter-guide), and unzip the `discord_game_sdk.so` file in your main app directory.

**Comment by mastef** [comment]
> This is happening because the latest release of the app is missing the Linux Discord Game SDK library, get it from [here](https://discord.com/developers/docs/game-sdk/sdk-starter-guide), and unzip the `discord_game_sdk.so` file in your main app directory.

@LiquidPL the file seems to be present though https://github.com/cswendrowski/FoundryVTT-Discord-Rich-Presence/tree/master/LocalApi/DiscordSdk

The advice I read somewhere else was that `*.so` files need to start with `lib` on linux systems. So trying to rename `discord_game_sdk.so` to `libdiscord_game_sdk.so` could help.
